- name: datatypes
  hosts: local
  connection: local
  vars:
    coursename: "aws with devops" #string
    duration: 120 #number
    topics:    #list
    - linux
    - git
    - shell
    - Docker
    live: true   # boolean
    tools:   # map/dict
      ci/cd: jenkins
      IAC: terraform
      orch: k8

- name: print course info
  ansible.builtin.debug:
    msg: "course is {{coursename}}, duration is {{duration}}, topics are {{topics}}, is live:{{live}} and tools are:{{tools}}"