- name: install nginx
  hosts: web
  become: yes
  tasks:
  # - name: install nginx
  #   ansible.builtin.dnf:
  #     name: nginx
  #     state: present
  #   when: ansible_os_family == "RedHat"

  - name: install nginx
    ansible.builtin.apt:
      name: nginx
      state: present
    when: ansible_os_family == "debian"