- name: configure frontend
  hosts: frontend
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: installed

  - name: enable & start nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes

  - name: delete directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent 

  - name: create directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory

  - name: download code 
    ansible.builtin.get_url:
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
      dest: /tmp/frontend.zip

  - name: unzip 
    ansible.builtin.unarchive:
      dest: /usr/share/nginx/html
      src: /tmp/frontend.zip
      remote_src: yes

  - name: copy 
    ansible.builtin.copy:
      src: expense.conf 
      dest: /etc/nginx/default.d/expense.conf

  - name: restart nginx
    ansible.builtin.service:
      name: nginx 
      state: restarted
      