[web]
44.223.62.246

[local]
localhost


# local means localhost mentioned above hosts. so therse variables applicable to hosts under [local]
[local:vars]
course="gcp with devops"
duration="120 Hours"
trainer="siva"