

; [local]
; localhost


# local means localhost mentioned above hosts. so these variables applicable to hosts under [local]
; [local:vars]
; course="gcp with devops"
; duration="120 Hours"
; trainer="siva"

; [web]
; 44.223.62.246 course="Terraform" duration="123hrs" trainer="siva" ansible_user=ec2-user ansible_password=DevOps321
; localhost course="Git" duration="13hrs" trainer="siva" ansible_user=ec2-user ansible_password=DevOps321


[web]
44.223.62.246 ansible_user=ec2-user ansible_password=DevOps321