- name: multi play
  hosts: local
  connection: local
  tasks:
  - name: play 1 and task 1
    ansible.builtin.debug:
    msg: hello from play 1 and task 1

- name: multi play 
  hosts: web
  connection: local
  tasks: 
  - name: paly 2 and task 1
    ansible.builtin.package:
    msg: hello from play 2 and task 1