- name: expense 
  hosts: web 
  become: yes
  tasks:
  - name: install mysql
    ansible.builtin.package:
      name: mysql-server
      state: installed
  
  - name: start mysql
    ansible.builtin.service:
      name: mysql
      state: started
      enabled: yes