- name: shell & command module
  hosts: web
  tasks:
  # - name: command module
  #   ansible.builtin.command: ls -ltr >/tmp/output.txt
  - name: shell module
    ansible.builtin.shell: ls -ltr >/tmp/output.txt
  - name: command module
    ansible.builtin.command: ls -ltr
    register: command_result
  - name: print the command_result
    ansible.builtin.debug:
      msg: "{{command_result}}"