- name: vars
  hosts: local
  connection: local
  vars:
    course: "devops with aws"
    duration: 120hrs
    trainer: sivakumar
  tasks:
  - name: print the variable
    vars: 
      course: Ansible
    ansible.builtin.debug:
      msg: "course is {{course}} , duration is {{duration}}, trainer is {{trainer}}"
