- name: vars from files
  hosts: local
  connection: local
  vars:
  - variables.yaml
  tasks: 
  - name: print course info
    ansible.builtin.debug:
      msg: "course is {{course}}, duration is {{duration}} and trainer is {{trainer}}"