- name: vars from args 
  hosts: local
  connection: local
  tasks:
  - name: vars from args
    ansible.builtin.debug:
      msg: "from {{greet}}"


      # ansible-playbook -i inventory.ini vars-args.yaml -e "greet=args"
